// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TimelineState {
  final BigInt position;
  final BigInt duration;
  final bool isPlaying;

  const TimelineState({
    required this.position,
    required this.duration,
    required this.isPlaying,
  });

  @override
  int get hashCode =>
      position.hashCode ^ duration.hashCode ^ isPlaying.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineState &&
          runtimeType == other.runtimeType &&
          position == other.position &&
          duration == other.duration &&
          isPlaying == other.isPlaying;
}

class VideoInfo {
  final int width;
  final int height;
  final double fps;
  final BigInt duration;

  const VideoInfo({
    required this.width,
    required this.height,
    required this.fps,
    required this.duration,
  });

  @override
  int get hashCode =>
      width.hashCode ^ height.hashCode ^ fps.hashCode ^ duration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          fps == other.fps &&
          duration == other.duration;
}
