// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'v2/core/types.dart';
import 'v2/flutter_bridge/api.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.7.0';

  @override
  int get rustContentHash => -1625191697;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flipedit',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  VideoEditorV2 crateV2FlutterBridgeApiVideoEditorV2New();

  String crateV2FlutterBridgeApiAddVideoFileV2({
    required VideoEditorV2 editor,
    required String filePath,
  });

  VideoEditorV2 crateV2FlutterBridgeApiCreateVideoEditorV2();

  TimelineState crateV2FlutterBridgeApiGetTimelineStateV2({
    required VideoEditorV2 editor,
  });

  VideoInfo? crateV2FlutterBridgeApiGetVideoInfoV2({
    required VideoEditorV2 editor,
  });

  void crateV2FlutterBridgeApiPausePreviewV2({required VideoEditorV2 editor});

  void crateV2FlutterBridgeApiPlayPreviewV2({required VideoEditorV2 editor});

  void crateV2FlutterBridgeApiSetClipDuration({
    required VideoEditorV2 editor,
    required String clipId,
    required BigInt durationNs,
  });

  void crateV2FlutterBridgeApiSetClipInPoint({
    required VideoEditorV2 editor,
    required String clipId,
    required BigInt inPointNs,
  });

  void crateV2FlutterBridgeApiSetClipStartTime({
    required VideoEditorV2 editor,
    required String clipId,
    required BigInt startTimeNs,
  });

  PlatformInt64 crateV2FlutterBridgeApiSetupPreviewV2({
    required VideoEditorV2 editor,
    required PlatformInt64 engineHandle,
    required int width,
    required int height,
  });

  String? crateV2FlutterBridgeApiSplitGesClipAtPosition({
    required VideoEditorV2 editor,
    required String clipId,
    required BigInt positionNs,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_VideoEditorV2;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_VideoEditorV2;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VideoEditorV2Ptr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  VideoEditorV2 crateV2FlutterBridgeApiVideoEditorV2New() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateV2FlutterBridgeApiVideoEditorV2NewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateV2FlutterBridgeApiVideoEditorV2NewConstMeta =>
      const TaskConstMeta(debugName: "VideoEditorV2_new", argNames: []);

  @override
  String crateV2FlutterBridgeApiAddVideoFileV2({
    required VideoEditorV2 editor,
    required String filePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
            editor,
            serializer,
          );
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateV2FlutterBridgeApiAddVideoFileV2ConstMeta,
        argValues: [editor, filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateV2FlutterBridgeApiAddVideoFileV2ConstMeta =>
      const TaskConstMeta(
        debugName: "add_video_file_v2",
        argNames: ["editor", "filePath"],
      );

  @override
  VideoEditorV2 crateV2FlutterBridgeApiCreateVideoEditorV2() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateV2FlutterBridgeApiCreateVideoEditorV2ConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateV2FlutterBridgeApiCreateVideoEditorV2ConstMeta =>
      const TaskConstMeta(debugName: "create_video_editor_v2", argNames: []);

  @override
  TimelineState crateV2FlutterBridgeApiGetTimelineStateV2({
    required VideoEditorV2 editor,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
            editor,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_timeline_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateV2FlutterBridgeApiGetTimelineStateV2ConstMeta,
        argValues: [editor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateV2FlutterBridgeApiGetTimelineStateV2ConstMeta =>
      const TaskConstMeta(
        debugName: "get_timeline_state_v2",
        argNames: ["editor"],
      );

  @override
  VideoInfo? crateV2FlutterBridgeApiGetVideoInfoV2({
    required VideoEditorV2 editor,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
            editor,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_video_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateV2FlutterBridgeApiGetVideoInfoV2ConstMeta,
        argValues: [editor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateV2FlutterBridgeApiGetVideoInfoV2ConstMeta =>
      const TaskConstMeta(debugName: "get_video_info_v2", argNames: ["editor"]);

  @override
  void crateV2FlutterBridgeApiPausePreviewV2({required VideoEditorV2 editor}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
            editor,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateV2FlutterBridgeApiPausePreviewV2ConstMeta,
        argValues: [editor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateV2FlutterBridgeApiPausePreviewV2ConstMeta =>
      const TaskConstMeta(debugName: "pause_preview_v2", argNames: ["editor"]);

  @override
  void crateV2FlutterBridgeApiPlayPreviewV2({required VideoEditorV2 editor}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
            editor,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateV2FlutterBridgeApiPlayPreviewV2ConstMeta,
        argValues: [editor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateV2FlutterBridgeApiPlayPreviewV2ConstMeta =>
      const TaskConstMeta(debugName: "play_preview_v2", argNames: ["editor"]);

  @override
  void crateV2FlutterBridgeApiSetClipDuration({
    required VideoEditorV2 editor,
    required String clipId,
    required BigInt durationNs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
            editor,
            serializer,
          );
          sse_encode_String(clipId, serializer);
          sse_encode_u_64(durationNs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateV2FlutterBridgeApiSetClipDurationConstMeta,
        argValues: [editor, clipId, durationNs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateV2FlutterBridgeApiSetClipDurationConstMeta =>
      const TaskConstMeta(
        debugName: "set_clip_duration",
        argNames: ["editor", "clipId", "durationNs"],
      );

  @override
  void crateV2FlutterBridgeApiSetClipInPoint({
    required VideoEditorV2 editor,
    required String clipId,
    required BigInt inPointNs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
            editor,
            serializer,
          );
          sse_encode_String(clipId, serializer);
          sse_encode_u_64(inPointNs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateV2FlutterBridgeApiSetClipInPointConstMeta,
        argValues: [editor, clipId, inPointNs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateV2FlutterBridgeApiSetClipInPointConstMeta =>
      const TaskConstMeta(
        debugName: "set_clip_in_point",
        argNames: ["editor", "clipId", "inPointNs"],
      );

  @override
  void crateV2FlutterBridgeApiSetClipStartTime({
    required VideoEditorV2 editor,
    required String clipId,
    required BigInt startTimeNs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
            editor,
            serializer,
          );
          sse_encode_String(clipId, serializer);
          sse_encode_u_64(startTimeNs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateV2FlutterBridgeApiSetClipStartTimeConstMeta,
        argValues: [editor, clipId, startTimeNs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateV2FlutterBridgeApiSetClipStartTimeConstMeta =>
      const TaskConstMeta(
        debugName: "set_clip_start_time",
        argNames: ["editor", "clipId", "startTimeNs"],
      );

  @override
  PlatformInt64 crateV2FlutterBridgeApiSetupPreviewV2({
    required VideoEditorV2 editor,
    required PlatformInt64 engineHandle,
    required int width,
    required int height,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
            editor,
            serializer,
          );
          sse_encode_i_64(engineHandle, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateV2FlutterBridgeApiSetupPreviewV2ConstMeta,
        argValues: [editor, engineHandle, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateV2FlutterBridgeApiSetupPreviewV2ConstMeta =>
      const TaskConstMeta(
        debugName: "setup_preview_v2",
        argNames: ["editor", "engineHandle", "width", "height"],
      );

  @override
  String? crateV2FlutterBridgeApiSplitGesClipAtPosition({
    required VideoEditorV2 editor,
    required String clipId,
    required BigInt positionNs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
            editor,
            serializer,
          );
          sse_encode_String(clipId, serializer);
          sse_encode_u_64(positionNs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateV2FlutterBridgeApiSplitGesClipAtPositionConstMeta,
        argValues: [editor, clipId, positionNs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateV2FlutterBridgeApiSplitGesClipAtPositionConstMeta =>
      const TaskConstMeta(
        debugName: "split_ges_clip_at_position",
        argNames: ["editor", "clipId", "positionNs"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_VideoEditorV2 =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_VideoEditorV2 =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  VideoEditorV2
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VideoEditorV2Impl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VideoEditorV2
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VideoEditorV2Impl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VideoEditorV2
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VideoEditorV2Impl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VideoEditorV2
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VideoEditorV2Impl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  VideoInfo dco_decode_box_autoadd_video_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_video_info(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  VideoInfo? dco_decode_opt_box_autoadd_video_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_video_info(raw);
  }

  @protected
  TimelineState dco_decode_timeline_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TimelineState(
      position: dco_decode_u_64(arr[0]),
      duration: dco_decode_u_64(arr[1]),
      isPlaying: dco_decode_bool(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VideoInfo dco_decode_video_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VideoInfo(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      fps: dco_decode_f_64(arr[2]),
      duration: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  VideoEditorV2
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VideoEditorV2Impl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VideoEditorV2
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VideoEditorV2Impl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VideoEditorV2
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VideoEditorV2Impl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VideoEditorV2
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VideoEditorV2Impl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  VideoInfo sse_decode_box_autoadd_video_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_video_info(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  VideoInfo? sse_decode_opt_box_autoadd_video_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_video_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TimelineState sse_decode_timeline_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_position = sse_decode_u_64(deserializer);
    var var_duration = sse_decode_u_64(deserializer);
    var var_isPlaying = sse_decode_bool(deserializer);
    return TimelineState(
      position: var_position,
      duration: var_duration,
      isPlaying: var_isPlaying,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VideoInfo sse_decode_video_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_fps = sse_decode_f_64(deserializer);
    var var_duration = sse_decode_u_64(deserializer);
    return VideoInfo(
      width: var_width,
      height: var_height,
      fps: var_fps,
      duration: var_duration,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
    VideoEditorV2 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VideoEditorV2Impl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
    VideoEditorV2 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VideoEditorV2Impl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
    VideoEditorV2 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VideoEditorV2Impl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoEditorV2(
    VideoEditorV2 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VideoEditorV2Impl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_video_info(
    VideoInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_video_info(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_video_info(
    VideoInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_video_info(self, serializer);
    }
  }

  @protected
  void sse_encode_timeline_state(TimelineState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.position, serializer);
    sse_encode_u_64(self.duration, serializer);
    sse_encode_bool(self.isPlaying, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_video_info(VideoInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_f_64(self.fps, serializer);
    sse_encode_u_64(self.duration, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class VideoEditorV2Impl extends RustOpaque implements VideoEditorV2 {
  // Not to be used by end users
  VideoEditorV2Impl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  VideoEditorV2Impl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_VideoEditorV2,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_VideoEditorV2,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_VideoEditorV2Ptr,
  );
}
