// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bridge.dart';
import 'api/simple.dart';
import 'common/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiBridgeInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.7.0';

  @override
  int get rustContentHash => 1128133065;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flipedit',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleGesTimelinePlayerDispose({
    required GesTimelinePlayer that,
  });

  BigInt crateApiSimpleGesTimelinePlayerGetCurrentFrameNumber({
    required GesTimelinePlayer that,
  });

  BigInt crateApiSimpleGesTimelinePlayerGetCurrentPositionMs({
    required GesTimelinePlayer that,
  });

  double crateApiSimpleGesTimelinePlayerGetCurrentPositionSeconds({
    required GesTimelinePlayer that,
  });

  int? crateApiSimpleGesTimelinePlayerGetDurationMs({
    required GesTimelinePlayer that,
  });

  BigInt crateApiSimpleGesTimelinePlayerGetLatestTextureId({
    required GesTimelinePlayer that,
  });

  int crateApiSimpleGesTimelinePlayerGetPositionMs({
    required GesTimelinePlayer that,
  });

  bool crateApiSimpleGesTimelinePlayerIsActivelyPlaying({
    required GesTimelinePlayer that,
  });

  bool crateApiSimpleGesTimelinePlayerIsPlaying({
    required GesTimelinePlayer that,
  });

  bool crateApiSimpleGesTimelinePlayerIsSeekable({
    required GesTimelinePlayer that,
  });

  Future<PlatformInt64> crateApiSimpleGesTimelinePlayerLoadTimeline({
    required GesTimelinePlayer that,
    required TimelineData timelineData,
    required PlatformInt64 engineHandle,
  });

  GesTimelinePlayer crateApiSimpleGesTimelinePlayerNew();

  Future<void> crateApiSimpleGesTimelinePlayerPause({
    required GesTimelinePlayer that,
  });

  Future<void> crateApiSimpleGesTimelinePlayerPlay({
    required GesTimelinePlayer that,
  });

  Future<void> crateApiSimpleGesTimelinePlayerSeekToPosition({
    required GesTimelinePlayer that,
    required int positionMs,
  });

  Future<void> crateApiSimpleGesTimelinePlayerSetTimelineDuration({
    required GesTimelinePlayer that,
    required BigInt durationMs,
  });

  Stream<(double, BigInt)> crateApiSimpleGesTimelinePlayerSetupPositionStream({
    required GesTimelinePlayer that,
  });

  Stream<int> crateApiSimpleGesTimelinePlayerSetupSeekCompletionStream({
    required GesTimelinePlayer that,
  });

  Future<void> crateApiSimpleGesTimelinePlayerStop({
    required GesTimelinePlayer that,
  });

  Future<void> crateApiSimpleGesTimelinePlayerUpdateClipTransform({
    required GesTimelinePlayer that,
    required int clipId,
    required double previewPositionX,
    required double previewPositionY,
    required double previewWidth,
    required double previewHeight,
  });

  void crateApiSimpleGesTimelinePlayerUpdatePosition({
    required GesTimelinePlayer that,
  });

  Future<void> crateApiSimpleTimelinePlayerDispose({
    required TimelinePlayer that,
  });

  BigInt crateApiSimpleTimelinePlayerGetLatestTextureId({
    required TimelinePlayer that,
  });

  int crateApiSimpleTimelinePlayerGetPositionMs({required TimelinePlayer that});

  bool crateApiSimpleTimelinePlayerIsPlaying({required TimelinePlayer that});

  Future<PlatformInt64> crateApiSimpleTimelinePlayerLoadTimeline({
    required TimelinePlayer that,
    required TimelineData timelineData,
    required PlatformInt64 engineHandle,
  });

  TimelinePlayer crateApiSimpleTimelinePlayerNew();

  Future<void> crateApiSimpleTimelinePlayerPause({
    required TimelinePlayer that,
  });

  Future<void> crateApiSimpleTimelinePlayerPlay({required TimelinePlayer that});

  Future<void> crateApiSimpleTimelinePlayerSetPositionMs({
    required TimelinePlayer that,
    required int positionMs,
  });

  Future<void> crateApiSimpleTimelinePlayerStop({required TimelinePlayer that});

  bool crateApiSimpleTimelinePlayerTestTimelineLogic({
    required TimelinePlayer that,
    required int positionMs,
  });

  Future<(GesTimelinePlayer, PlatformInt64)>
  crateApiSimpleCreateGesTimelinePlayer({
    required TimelineData timelineData,
    required PlatformInt64 engineHandle,
  });

  PlatformInt64 crateApiSimpleCreateVideoTexture({
    required int width,
    required int height,
    required PlatformInt64 engineHandle,
  });

  BigInt crateApiSimpleGetTextureCount();

  BigInt crateApiSimpleGetVideoDurationMs({required String filePath});

  String crateApiBridgeGreet({required String name});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiBridgeInitApp();

  bool crateApiSimpleUpdateVideoFrame({required FrameData frameData});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GesTimelinePlayer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GesTimelinePlayer;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_GesTimelinePlayerPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TimelinePlayer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TimelinePlayer;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TimelinePlayerPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleGesTimelinePlayerDispose({
    required GesTimelinePlayer that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerDisposeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGesTimelinePlayerDisposeConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_dispose",
        argNames: ["that"],
      );

  @override
  BigInt crateApiSimpleGesTimelinePlayerGetCurrentFrameNumber({
    required GesTimelinePlayer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiSimpleGesTimelinePlayerGetCurrentFrameNumberConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleGesTimelinePlayerGetCurrentFrameNumberConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_get_current_frame_number",
        argNames: ["that"],
      );

  @override
  BigInt crateApiSimpleGesTimelinePlayerGetCurrentPositionMs({
    required GesTimelinePlayer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiSimpleGesTimelinePlayerGetCurrentPositionMsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleGesTimelinePlayerGetCurrentPositionMsConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_get_current_position_ms",
        argNames: ["that"],
      );

  @override
  double crateApiSimpleGesTimelinePlayerGetCurrentPositionSeconds({
    required GesTimelinePlayer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiSimpleGesTimelinePlayerGetCurrentPositionSecondsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleGesTimelinePlayerGetCurrentPositionSecondsConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_get_current_position_seconds",
        argNames: ["that"],
      );

  @override
  int? crateApiSimpleGesTimelinePlayerGetDurationMs({
    required GesTimelinePlayer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerGetDurationMsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGesTimelinePlayerGetDurationMsConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_get_duration_ms",
        argNames: ["that"],
      );

  @override
  BigInt crateApiSimpleGesTimelinePlayerGetLatestTextureId({
    required GesTimelinePlayer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerGetLatestTextureIdConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleGesTimelinePlayerGetLatestTextureIdConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_get_latest_texture_id",
        argNames: ["that"],
      );

  @override
  int crateApiSimpleGesTimelinePlayerGetPositionMs({
    required GesTimelinePlayer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerGetPositionMsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGesTimelinePlayerGetPositionMsConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_get_position_ms",
        argNames: ["that"],
      );

  @override
  bool crateApiSimpleGesTimelinePlayerIsActivelyPlaying({
    required GesTimelinePlayer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerIsActivelyPlayingConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleGesTimelinePlayerIsActivelyPlayingConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_is_actively_playing",
        argNames: ["that"],
      );

  @override
  bool crateApiSimpleGesTimelinePlayerIsPlaying({
    required GesTimelinePlayer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerIsPlayingConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGesTimelinePlayerIsPlayingConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_is_playing",
        argNames: ["that"],
      );

  @override
  bool crateApiSimpleGesTimelinePlayerIsSeekable({
    required GesTimelinePlayer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerIsSeekableConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGesTimelinePlayerIsSeekableConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_is_seekable",
        argNames: ["that"],
      );

  @override
  Future<PlatformInt64> crateApiSimpleGesTimelinePlayerLoadTimeline({
    required GesTimelinePlayer that,
    required TimelineData timelineData,
    required PlatformInt64 engineHandle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          sse_encode_box_autoadd_timeline_data(timelineData, serializer);
          sse_encode_i_64(engineHandle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerLoadTimelineConstMeta,
        argValues: [that, timelineData, engineHandle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGesTimelinePlayerLoadTimelineConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_load_timeline",
        argNames: ["that", "timelineData", "engineHandle"],
      );

  @override
  GesTimelinePlayer crateApiSimpleGesTimelinePlayerNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGesTimelinePlayerNewConstMeta =>
      const TaskConstMeta(debugName: "GesTimelinePlayer_new", argNames: []);

  @override
  Future<void> crateApiSimpleGesTimelinePlayerPause({
    required GesTimelinePlayer that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerPauseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGesTimelinePlayerPauseConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_pause",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiSimpleGesTimelinePlayerPlay({
    required GesTimelinePlayer that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerPlayConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGesTimelinePlayerPlayConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_play",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiSimpleGesTimelinePlayerSeekToPosition({
    required GesTimelinePlayer that,
    required int positionMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          sse_encode_i_32(positionMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerSeekToPositionConstMeta,
        argValues: [that, positionMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGesTimelinePlayerSeekToPositionConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_seek_to_position",
        argNames: ["that", "positionMs"],
      );

  @override
  Future<void> crateApiSimpleGesTimelinePlayerSetTimelineDuration({
    required GesTimelinePlayer that,
    required BigInt durationMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          sse_encode_u_64(durationMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerSetTimelineDurationConstMeta,
        argValues: [that, durationMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleGesTimelinePlayerSetTimelineDurationConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_set_timeline_duration",
        argNames: ["that", "durationMs"],
      );

  @override
  Stream<(double, BigInt)> crateApiSimpleGesTimelinePlayerSetupPositionStream({
    required GesTimelinePlayer that,
  }) {
    final sink = RustStreamSink<(double, BigInt)>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
              that,
              serializer,
            );
            sse_encode_StreamSink_record_f_64_u_64_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 17,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta:
              kCrateApiSimpleGesTimelinePlayerSetupPositionStreamConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiSimpleGesTimelinePlayerSetupPositionStreamConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_setup_position_stream",
        argNames: ["that", "sink"],
      );

  @override
  Stream<int> crateApiSimpleGesTimelinePlayerSetupSeekCompletionStream({
    required GesTimelinePlayer that,
  }) {
    final sink = RustStreamSink<int>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
              that,
              serializer,
            );
            sse_encode_StreamSink_i_32_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 18,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta:
              kCrateApiSimpleGesTimelinePlayerSetupSeekCompletionStreamConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiSimpleGesTimelinePlayerSetupSeekCompletionStreamConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_setup_seek_completion_stream",
        argNames: ["that", "sink"],
      );

  @override
  Future<void> crateApiSimpleGesTimelinePlayerStop({
    required GesTimelinePlayer that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerStopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGesTimelinePlayerStopConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_stop",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiSimpleGesTimelinePlayerUpdateClipTransform({
    required GesTimelinePlayer that,
    required int clipId,
    required double previewPositionX,
    required double previewPositionY,
    required double previewWidth,
    required double previewHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          sse_encode_i_32(clipId, serializer);
          sse_encode_f_64(previewPositionX, serializer);
          sse_encode_f_64(previewPositionY, serializer);
          sse_encode_f_64(previewWidth, serializer);
          sse_encode_f_64(previewHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerUpdateClipTransformConstMeta,
        argValues: [
          that,
          clipId,
          previewPositionX,
          previewPositionY,
          previewWidth,
          previewHeight,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleGesTimelinePlayerUpdateClipTransformConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_update_clip_transform",
        argNames: [
          "that",
          "clipId",
          "previewPositionX",
          "previewPositionY",
          "previewWidth",
          "previewHeight",
        ],
      );

  @override
  void crateApiSimpleGesTimelinePlayerUpdatePosition({
    required GesTimelinePlayer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGesTimelinePlayerUpdatePositionConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGesTimelinePlayerUpdatePositionConstMeta =>
      const TaskConstMeta(
        debugName: "GesTimelinePlayer_update_position",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiSimpleTimelinePlayerDispose({
    required TimelinePlayer that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleTimelinePlayerDisposeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTimelinePlayerDisposeConstMeta =>
      const TaskConstMeta(
        debugName: "TimelinePlayer_dispose",
        argNames: ["that"],
      );

  @override
  BigInt crateApiSimpleTimelinePlayerGetLatestTextureId({
    required TimelinePlayer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTimelinePlayerGetLatestTextureIdConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTimelinePlayerGetLatestTextureIdConstMeta =>
      const TaskConstMeta(
        debugName: "TimelinePlayer_get_latest_texture_id",
        argNames: ["that"],
      );

  @override
  int crateApiSimpleTimelinePlayerGetPositionMs({
    required TimelinePlayer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTimelinePlayerGetPositionMsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTimelinePlayerGetPositionMsConstMeta =>
      const TaskConstMeta(
        debugName: "TimelinePlayer_get_position_ms",
        argNames: ["that"],
      );

  @override
  bool crateApiSimpleTimelinePlayerIsPlaying({required TimelinePlayer that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTimelinePlayerIsPlayingConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTimelinePlayerIsPlayingConstMeta =>
      const TaskConstMeta(
        debugName: "TimelinePlayer_is_playing",
        argNames: ["that"],
      );

  @override
  Future<PlatformInt64> crateApiSimpleTimelinePlayerLoadTimeline({
    required TimelinePlayer that,
    required TimelineData timelineData,
    required PlatformInt64 engineHandle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
            that,
            serializer,
          );
          sse_encode_box_autoadd_timeline_data(timelineData, serializer);
          sse_encode_i_64(engineHandle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleTimelinePlayerLoadTimelineConstMeta,
        argValues: [that, timelineData, engineHandle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTimelinePlayerLoadTimelineConstMeta =>
      const TaskConstMeta(
        debugName: "TimelinePlayer_load_timeline",
        argNames: ["that", "timelineData", "engineHandle"],
      );

  @override
  TimelinePlayer crateApiSimpleTimelinePlayerNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTimelinePlayerNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTimelinePlayerNewConstMeta =>
      const TaskConstMeta(debugName: "TimelinePlayer_new", argNames: []);

  @override
  Future<void> crateApiSimpleTimelinePlayerPause({
    required TimelinePlayer that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleTimelinePlayerPauseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTimelinePlayerPauseConstMeta =>
      const TaskConstMeta(
        debugName: "TimelinePlayer_pause",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiSimpleTimelinePlayerPlay({
    required TimelinePlayer that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleTimelinePlayerPlayConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTimelinePlayerPlayConstMeta =>
      const TaskConstMeta(debugName: "TimelinePlayer_play", argNames: ["that"]);

  @override
  Future<void> crateApiSimpleTimelinePlayerSetPositionMs({
    required TimelinePlayer that,
    required int positionMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
            that,
            serializer,
          );
          sse_encode_i_32(positionMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTimelinePlayerSetPositionMsConstMeta,
        argValues: [that, positionMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTimelinePlayerSetPositionMsConstMeta =>
      const TaskConstMeta(
        debugName: "TimelinePlayer_set_position_ms",
        argNames: ["that", "positionMs"],
      );

  @override
  Future<void> crateApiSimpleTimelinePlayerStop({
    required TimelinePlayer that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleTimelinePlayerStopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTimelinePlayerStopConstMeta =>
      const TaskConstMeta(debugName: "TimelinePlayer_stop", argNames: ["that"]);

  @override
  bool crateApiSimpleTimelinePlayerTestTimelineLogic({
    required TimelinePlayer that,
    required int positionMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
            that,
            serializer,
          );
          sse_encode_i_32(positionMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTimelinePlayerTestTimelineLogicConstMeta,
        argValues: [that, positionMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTimelinePlayerTestTimelineLogicConstMeta =>
      const TaskConstMeta(
        debugName: "TimelinePlayer_test_timeline_logic",
        argNames: ["that", "positionMs"],
      );

  @override
  Future<(GesTimelinePlayer, PlatformInt64)>
  crateApiSimpleCreateGesTimelinePlayer({
    required TimelineData timelineData,
    required PlatformInt64 engineHandle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_timeline_data(timelineData, serializer);
          sse_encode_i_64(engineHandle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_ges_timeline_player_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleCreateGesTimelinePlayerConstMeta,
        argValues: [timelineData, engineHandle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCreateGesTimelinePlayerConstMeta =>
      const TaskConstMeta(
        debugName: "create_ges_timeline_player",
        argNames: ["timelineData", "engineHandle"],
      );

  @override
  PlatformInt64 crateApiSimpleCreateVideoTexture({
    required int width,
    required int height,
    required PlatformInt64 engineHandle,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_i_64(engineHandle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleCreateVideoTextureConstMeta,
        argValues: [width, height, engineHandle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCreateVideoTextureConstMeta =>
      const TaskConstMeta(
        debugName: "create_video_texture",
        argNames: ["width", "height", "engineHandle"],
      );

  @override
  BigInt crateApiSimpleGetTextureCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetTextureCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetTextureCountConstMeta =>
      const TaskConstMeta(debugName: "get_texture_count", argNames: []);

  @override
  BigInt crateApiSimpleGetVideoDurationMs({required String filePath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGetVideoDurationMsConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetVideoDurationMsConstMeta =>
      const TaskConstMeta(
        debugName: "get_video_duration_ms",
        argNames: ["filePath"],
      );

  @override
  String crateApiBridgeGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiBridgeInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiSimpleUpdateVideoFrame({required FrameData frameData}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_frame_data(frameData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleUpdateVideoFrameConstMeta,
        argValues: [frameData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleUpdateVideoFrameConstMeta =>
      const TaskConstMeta(
        debugName: "update_video_frame",
        argNames: ["frameData"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_GesTimelinePlayer =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_GesTimelinePlayer =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_TimelinePlayer =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_TimelinePlayer =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  GesTimelinePlayer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GesTimelinePlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TimelinePlayer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TimelinePlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GesTimelinePlayer
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GesTimelinePlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TimelinePlayer
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TimelinePlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GesTimelinePlayer
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GesTimelinePlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TimelinePlayer
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TimelinePlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  GesTimelinePlayer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GesTimelinePlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TimelinePlayer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TimelinePlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<int> dco_decode_StreamSink_i_32_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<(double, BigInt)> dco_decode_StreamSink_record_f_64_u_64_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FrameData dco_decode_box_autoadd_frame_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_frame_data(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  TimelineData dco_decode_box_autoadd_timeline_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_timeline_data(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FrameData dco_decode_frame_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FrameData(
      data: dco_decode_list_prim_u_8_strict(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      textureId: dco_decode_opt_box_autoadd_u_64(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TimelineClip> dco_decode_list_timeline_clip(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_timeline_clip).toList();
  }

  @protected
  List<TimelineTrack> dco_decode_list_timeline_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_timeline_track).toList();
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  (GesTimelinePlayer, PlatformInt64)
  dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_ges_timeline_player_i_64(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
        arr[0],
      ),
      dco_decode_i_64(arr[1]),
    );
  }

  @protected
  (double, BigInt) dco_decode_record_f_64_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_f_64(arr[0]), dco_decode_u_64(arr[1]));
  }

  @protected
  TimelineClip dco_decode_timeline_clip(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return TimelineClip(
      id: dco_decode_opt_box_autoadd_i_32(arr[0]),
      trackId: dco_decode_i_32(arr[1]),
      sourcePath: dco_decode_String(arr[2]),
      startTimeOnTrackMs: dco_decode_i_32(arr[3]),
      endTimeOnTrackMs: dco_decode_i_32(arr[4]),
      startTimeInSourceMs: dco_decode_i_32(arr[5]),
      endTimeInSourceMs: dco_decode_i_32(arr[6]),
      previewPositionX: dco_decode_f_64(arr[7]),
      previewPositionY: dco_decode_f_64(arr[8]),
      previewWidth: dco_decode_f_64(arr[9]),
      previewHeight: dco_decode_f_64(arr[10]),
    );
  }

  @protected
  TimelineData dco_decode_timeline_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return TimelineData(tracks: dco_decode_list_timeline_track(arr[0]));
  }

  @protected
  TimelineTrack dco_decode_timeline_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TimelineTrack(
      id: dco_decode_i_32(arr[0]),
      name: dco_decode_String(arr[1]),
      clips: dco_decode_list_timeline_clip(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  GesTimelinePlayer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GesTimelinePlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TimelinePlayer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TimelinePlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GesTimelinePlayer
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GesTimelinePlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TimelinePlayer
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TimelinePlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GesTimelinePlayer
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GesTimelinePlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TimelinePlayer
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TimelinePlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  GesTimelinePlayer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GesTimelinePlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  TimelinePlayer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TimelinePlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<int> sse_decode_StreamSink_i_32_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<(double, BigInt)> sse_decode_StreamSink_record_f_64_u_64_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FrameData sse_decode_box_autoadd_frame_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_frame_data(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  TimelineData sse_decode_box_autoadd_timeline_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_timeline_data(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FrameData sse_decode_frame_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_textureId = sse_decode_opt_box_autoadd_u_64(deserializer);
    return FrameData(
      data: var_data,
      width: var_width,
      height: var_height,
      textureId: var_textureId,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TimelineClip> sse_decode_list_timeline_clip(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TimelineClip>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_timeline_clip(deserializer));
    }
    return ans_;
  }

  @protected
  List<TimelineTrack> sse_decode_list_timeline_track(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TimelineTrack>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_timeline_track(deserializer));
    }
    return ans_;
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (GesTimelinePlayer, PlatformInt64)
  sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_ges_timeline_player_i_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 =
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
          deserializer,
        );
    var var_field1 = sse_decode_i_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (double, BigInt) sse_decode_record_f_64_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_f_64(deserializer);
    var var_field1 = sse_decode_u_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  TimelineClip sse_decode_timeline_clip(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_trackId = sse_decode_i_32(deserializer);
    var var_sourcePath = sse_decode_String(deserializer);
    var var_startTimeOnTrackMs = sse_decode_i_32(deserializer);
    var var_endTimeOnTrackMs = sse_decode_i_32(deserializer);
    var var_startTimeInSourceMs = sse_decode_i_32(deserializer);
    var var_endTimeInSourceMs = sse_decode_i_32(deserializer);
    var var_previewPositionX = sse_decode_f_64(deserializer);
    var var_previewPositionY = sse_decode_f_64(deserializer);
    var var_previewWidth = sse_decode_f_64(deserializer);
    var var_previewHeight = sse_decode_f_64(deserializer);
    return TimelineClip(
      id: var_id,
      trackId: var_trackId,
      sourcePath: var_sourcePath,
      startTimeOnTrackMs: var_startTimeOnTrackMs,
      endTimeOnTrackMs: var_endTimeOnTrackMs,
      startTimeInSourceMs: var_startTimeInSourceMs,
      endTimeInSourceMs: var_endTimeInSourceMs,
      previewPositionX: var_previewPositionX,
      previewPositionY: var_previewPositionY,
      previewWidth: var_previewWidth,
      previewHeight: var_previewHeight,
    );
  }

  @protected
  TimelineData sse_decode_timeline_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tracks = sse_decode_list_timeline_track(deserializer);
    return TimelineData(tracks: var_tracks);
  }

  @protected
  TimelineTrack sse_decode_timeline_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_clips = sse_decode_list_timeline_clip(deserializer);
    return TimelineTrack(id: var_id, name: var_name, clips: var_clips);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
    GesTimelinePlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GesTimelinePlayerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
    TimelinePlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TimelinePlayerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
    GesTimelinePlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GesTimelinePlayerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
    TimelinePlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TimelinePlayerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
    GesTimelinePlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GesTimelinePlayerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
    TimelinePlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TimelinePlayerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
    GesTimelinePlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as GesTimelinePlayerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTimelinePlayer(
    TimelinePlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as TimelinePlayerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_i_32_Sse(
    RustStreamSink<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_record_f_64_u_64_Sse(
    RustStreamSink<(double, BigInt)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_f_64_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_frame_data(
    FrameData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_frame_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_timeline_data(
    TimelineData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_timeline_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_frame_data(FrameData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.data, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_opt_box_autoadd_u_64(self.textureId, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_timeline_clip(
    List<TimelineClip> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_timeline_clip(item, serializer);
    }
  }

  @protected
  void sse_encode_list_timeline_track(
    List<TimelineTrack> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_timeline_track(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void
  sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_ges_timeline_player_i_64(
    (GesTimelinePlayer, PlatformInt64) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGESTimelinePlayer(
      self.$1,
      serializer,
    );
    sse_encode_i_64(self.$2, serializer);
  }

  @protected
  void sse_encode_record_f_64_u_64(
    (double, BigInt) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.$1, serializer);
    sse_encode_u_64(self.$2, serializer);
  }

  @protected
  void sse_encode_timeline_clip(TimelineClip self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_32(self.id, serializer);
    sse_encode_i_32(self.trackId, serializer);
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_i_32(self.startTimeOnTrackMs, serializer);
    sse_encode_i_32(self.endTimeOnTrackMs, serializer);
    sse_encode_i_32(self.startTimeInSourceMs, serializer);
    sse_encode_i_32(self.endTimeInSourceMs, serializer);
    sse_encode_f_64(self.previewPositionX, serializer);
    sse_encode_f_64(self.previewPositionY, serializer);
    sse_encode_f_64(self.previewWidth, serializer);
    sse_encode_f_64(self.previewHeight, serializer);
  }

  @protected
  void sse_encode_timeline_data(TimelineData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_timeline_track(self.tracks, serializer);
  }

  @protected
  void sse_encode_timeline_track(TimelineTrack self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_timeline_clip(self.clips, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class GesTimelinePlayerImpl extends RustOpaque implements GesTimelinePlayer {
  // Not to be used by end users
  GesTimelinePlayerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  GesTimelinePlayerImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_GesTimelinePlayer,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_GesTimelinePlayer,
    rustArcDecrementStrongCountPtr:
        RustLib
            .instance
            .api
            .rust_arc_decrement_strong_count_GesTimelinePlayerPtr,
  );

  Future<void> dispose() =>
      RustLib.instance.api.crateApiSimpleGesTimelinePlayerDispose(that: this);

  /// Get current frame number based on position and frame rate
  BigInt getCurrentFrameNumber() => RustLib.instance.api
      .crateApiSimpleGesTimelinePlayerGetCurrentFrameNumber(that: this);

  /// Get current playback position in milliseconds
  BigInt getCurrentPositionMs() => RustLib.instance.api
      .crateApiSimpleGesTimelinePlayerGetCurrentPositionMs(that: this);

  /// Get current playback position in seconds
  double getCurrentPositionSeconds() => RustLib.instance.api
      .crateApiSimpleGesTimelinePlayerGetCurrentPositionSeconds(that: this);

  int? getDurationMs() => RustLib.instance.api
      .crateApiSimpleGesTimelinePlayerGetDurationMs(that: this);

  BigInt getLatestTextureId() => RustLib.instance.api
      .crateApiSimpleGesTimelinePlayerGetLatestTextureId(that: this);

  int getPositionMs() => RustLib.instance.api
      .crateApiSimpleGesTimelinePlayerGetPositionMs(that: this);

  /// Check if pipeline is actively playing (for optimizing position update frequency)
  bool isActivelyPlaying() => RustLib.instance.api
      .crateApiSimpleGesTimelinePlayerIsActivelyPlaying(that: this);

  bool isPlaying() =>
      RustLib.instance.api.crateApiSimpleGesTimelinePlayerIsPlaying(that: this);

  bool isSeekable() => RustLib.instance.api
      .crateApiSimpleGesTimelinePlayerIsSeekable(that: this);

  Future<PlatformInt64> loadTimeline({
    required TimelineData timelineData,
    required PlatformInt64 engineHandle,
  }) => RustLib.instance.api.crateApiSimpleGesTimelinePlayerLoadTimeline(
    that: this,
    timelineData: timelineData,
    engineHandle: engineHandle,
  );

  Future<void> pause() =>
      RustLib.instance.api.crateApiSimpleGesTimelinePlayerPause(that: this);

  Future<void> play() =>
      RustLib.instance.api.crateApiSimpleGesTimelinePlayerPlay(that: this);

  Future<void> seekToPosition({required int positionMs}) =>
      RustLib.instance.api.crateApiSimpleGesTimelinePlayerSeekToPosition(
        that: this,
        positionMs: positionMs,
      );

  /// Set the timeline duration explicitly (called from Flutter when clips change)
  Future<void> setTimelineDuration({required BigInt durationMs}) =>
      RustLib.instance.api.crateApiSimpleGesTimelinePlayerSetTimelineDuration(
        that: this,
        durationMs: durationMs,
      );

  Stream<(double, BigInt)> setupPositionStream() => RustLib.instance.api
      .crateApiSimpleGesTimelinePlayerSetupPositionStream(that: this);

  Stream<int> setupSeekCompletionStream() => RustLib.instance.api
      .crateApiSimpleGesTimelinePlayerSetupSeekCompletionStream(that: this);

  Future<void> stop() =>
      RustLib.instance.api.crateApiSimpleGesTimelinePlayerStop(that: this);

  /// Update a specific clip's transform properties without reloading the entire timeline
  Future<void> updateClipTransform({
    required int clipId,
    required double previewPositionX,
    required double previewPositionY,
    required double previewWidth,
    required double previewHeight,
  }) => RustLib.instance.api.crateApiSimpleGesTimelinePlayerUpdateClipTransform(
    that: this,
    clipId: clipId,
    previewPositionX: previewPositionX,
    previewPositionY: previewPositionY,
    previewWidth: previewWidth,
    previewHeight: previewHeight,
  );

  /// Update position from GStreamer pipeline - call this regularly for smooth playhead updates
  /// According to GES guide, this should be called every 40-100ms during playback
  void updatePosition() => RustLib.instance.api
      .crateApiSimpleGesTimelinePlayerUpdatePosition(that: this);
}

@sealed
class TimelinePlayerImpl extends RustOpaque implements TimelinePlayer {
  // Not to be used by end users
  TimelinePlayerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TimelinePlayerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TimelinePlayer,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TimelinePlayer,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TimelinePlayerPtr,
  );

  Future<void> dispose() =>
      RustLib.instance.api.crateApiSimpleTimelinePlayerDispose(that: this);

  /// Get the latest texture ID for GPU-based rendering
  BigInt getLatestTextureId() => RustLib.instance.api
      .crateApiSimpleTimelinePlayerGetLatestTextureId(that: this);

  int getPositionMs() => RustLib.instance.api
      .crateApiSimpleTimelinePlayerGetPositionMs(that: this);

  bool isPlaying() =>
      RustLib.instance.api.crateApiSimpleTimelinePlayerIsPlaying(that: this);

  Future<PlatformInt64> loadTimeline({
    required TimelineData timelineData,
    required PlatformInt64 engineHandle,
  }) => RustLib.instance.api.crateApiSimpleTimelinePlayerLoadTimeline(
    that: this,
    timelineData: timelineData,
    engineHandle: engineHandle,
  );

  Future<void> pause() =>
      RustLib.instance.api.crateApiSimpleTimelinePlayerPause(that: this);

  Future<void> play() =>
      RustLib.instance.api.crateApiSimpleTimelinePlayerPlay(that: this);

  Future<void> setPositionMs({required int positionMs}) =>
      RustLib.instance.api.crateApiSimpleTimelinePlayerSetPositionMs(
        that: this,
        positionMs: positionMs,
      );

  Future<void> stop() =>
      RustLib.instance.api.crateApiSimpleTimelinePlayerStop(that: this);

  /// Test method to verify timeline logic - set position and check if frame should be shown
  bool testTimelineLogic({required int positionMs}) =>
      RustLib.instance.api.crateApiSimpleTimelinePlayerTestTimelineLogic(
        that: this,
        positionMs: positionMs,
      );
}
