// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../core/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These types are ignored because they are not used by any `pub` functions: `SimplePixelDataProvider`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `get_payload`

VideoEditorV2 createVideoEditorV2() =>
    RustLib.instance.api.crateV2FlutterBridgeApiCreateVideoEditorV2();

String addVideoFileV2({
  required VideoEditorV2 editor,
  required String filePath,
}) => RustLib.instance.api.crateV2FlutterBridgeApiAddVideoFileV2(
  editor: editor,
  filePath: filePath,
);

PlatformInt64 setupPreviewV2({
  required VideoEditorV2 editor,
  required PlatformInt64 engineHandle,
  required int width,
  required int height,
}) => RustLib.instance.api.crateV2FlutterBridgeApiSetupPreviewV2(
  editor: editor,
  engineHandle: engineHandle,
  width: width,
  height: height,
);

void playPreviewV2({required VideoEditorV2 editor}) =>
    RustLib.instance.api.crateV2FlutterBridgeApiPlayPreviewV2(editor: editor);

void pausePreviewV2({required VideoEditorV2 editor}) =>
    RustLib.instance.api.crateV2FlutterBridgeApiPausePreviewV2(editor: editor);

VideoInfo? getVideoInfoV2({required VideoEditorV2 editor}) =>
    RustLib.instance.api.crateV2FlutterBridgeApiGetVideoInfoV2(editor: editor);

TimelineState getTimelineStateV2({required VideoEditorV2 editor}) => RustLib
    .instance
    .api
    .crateV2FlutterBridgeApiGetTimelineStateV2(editor: editor);

void setClipStartTime({
  required VideoEditorV2 editor,
  required String clipId,
  required BigInt startTimeNs,
}) => RustLib.instance.api.crateV2FlutterBridgeApiSetClipStartTime(
  editor: editor,
  clipId: clipId,
  startTimeNs: startTimeNs,
);

void setClipDuration({
  required VideoEditorV2 editor,
  required String clipId,
  required BigInt durationNs,
}) => RustLib.instance.api.crateV2FlutterBridgeApiSetClipDuration(
  editor: editor,
  clipId: clipId,
  durationNs: durationNs,
);

void setClipInPoint({
  required VideoEditorV2 editor,
  required String clipId,
  required BigInt inPointNs,
}) => RustLib.instance.api.crateV2FlutterBridgeApiSetClipInPoint(
  editor: editor,
  clipId: clipId,
  inPointNs: inPointNs,
);

String? splitGesClipAtPosition({
  required VideoEditorV2 editor,
  required String clipId,
  required BigInt positionNs,
}) => RustLib.instance.api.crateV2FlutterBridgeApiSplitGesClipAtPosition(
  editor: editor,
  clipId: clipId,
  positionNs: positionNs,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VideoEditorV2>>
abstract class VideoEditorV2 implements RustOpaqueInterface {
  factory VideoEditorV2() =>
      RustLib.instance.api.crateV2FlutterBridgeApiVideoEditorV2New();
}
