// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Data structure for clip placement results that can cross the FFI boundary
class ClipPlacementResult {
  final int? clipId;
  final int trackId;
  final BigInt startTimeMs;
  final BigInt endTimeMs;
  final BigInt startTimeInSourceMs;
  final BigInt endTimeInSourceMs;
  final List<OverlapInfo> overlappingClips;
  final bool success;

  const ClipPlacementResult({
    this.clipId,
    required this.trackId,
    required this.startTimeMs,
    required this.endTimeMs,
    required this.startTimeInSourceMs,
    required this.endTimeInSourceMs,
    required this.overlappingClips,
    required this.success,
  });

  @override
  int get hashCode =>
      clipId.hashCode ^
      trackId.hashCode ^
      startTimeMs.hashCode ^
      endTimeMs.hashCode ^
      startTimeInSourceMs.hashCode ^
      endTimeInSourceMs.hashCode ^
      overlappingClips.hashCode ^
      success.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClipPlacementResult &&
          runtimeType == other.runtimeType &&
          clipId == other.clipId &&
          trackId == other.trackId &&
          startTimeMs == other.startTimeMs &&
          endTimeMs == other.endTimeMs &&
          startTimeInSourceMs == other.startTimeInSourceMs &&
          endTimeInSourceMs == other.endTimeInSourceMs &&
          overlappingClips == other.overlappingClips &&
          success == other.success;
}

/// Overlap information that can cross the FFI boundary
class OverlapInfo {
  final int clipId;
  final BigInt startTimeMs;
  final BigInt endTimeMs;
  final BigInt overlapStartMs;
  final BigInt overlapEndMs;
  final String actionType;
  final BigInt? actionTimeMs;

  const OverlapInfo({
    required this.clipId,
    required this.startTimeMs,
    required this.endTimeMs,
    required this.overlapStartMs,
    required this.overlapEndMs,
    required this.actionType,
    this.actionTimeMs,
  });

  @override
  int get hashCode =>
      clipId.hashCode ^
      startTimeMs.hashCode ^
      endTimeMs.hashCode ^
      overlapStartMs.hashCode ^
      overlapEndMs.hashCode ^
      actionType.hashCode ^
      actionTimeMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OverlapInfo &&
          runtimeType == other.runtimeType &&
          clipId == other.clipId &&
          startTimeMs == other.startTimeMs &&
          endTimeMs == other.endTimeMs &&
          overlapStartMs == other.overlapStartMs &&
          overlapEndMs == other.overlapEndMs &&
          actionType == other.actionType &&
          actionTimeMs == other.actionTimeMs;
}
