// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TimelineClipData {
  final int id;
  final int trackId;
  final String sourcePath;
  final PlatformInt64 startTimeOnTrackMs;
  final PlatformInt64 endTimeOnTrackMs;
  final PlatformInt64 startTimeInSourceMs;
  final PlatformInt64 endTimeInSourceMs;
  final PlatformInt64 sourceDurationMs;

  const TimelineClipData({
    required this.id,
    required this.trackId,
    required this.sourcePath,
    required this.startTimeOnTrackMs,
    required this.endTimeOnTrackMs,
    required this.startTimeInSourceMs,
    required this.endTimeInSourceMs,
    required this.sourceDurationMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      trackId.hashCode ^
      sourcePath.hashCode ^
      startTimeOnTrackMs.hashCode ^
      endTimeOnTrackMs.hashCode ^
      startTimeInSourceMs.hashCode ^
      endTimeInSourceMs.hashCode ^
      sourceDurationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineClipData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          trackId == other.trackId &&
          sourcePath == other.sourcePath &&
          startTimeOnTrackMs == other.startTimeOnTrackMs &&
          endTimeOnTrackMs == other.endTimeOnTrackMs &&
          startTimeInSourceMs == other.startTimeInSourceMs &&
          endTimeInSourceMs == other.endTimeInSourceMs &&
          sourceDurationMs == other.sourceDurationMs;
}
