// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FrameData {
  final Uint8List data;
  final int width;
  final int height;

  const FrameData({
    required this.data,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => data.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameData &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          width == other.width &&
          height == other.height;
}
