// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../common/types.dart';
import '../frb_generated.dart';
import '../video/timeline_composer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

PlatformInt64 timelineComposerCreate() =>
    RustLib.instance.api.crateApiSimpleTimelineComposerCreate();

void timelineComposerSetTexturePtr({
  required PlatformInt64 handle,
  required PlatformInt64 ptr,
}) => RustLib.instance.api.crateApiSimpleTimelineComposerSetTexturePtr(
  handle: handle,
  ptr: ptr,
);

Future<void> timelineComposerUpdateTimeline({
  required PlatformInt64 handle,
  required List<TimelineClipData> clips,
}) => RustLib.instance.api.crateApiSimpleTimelineComposerUpdateTimeline(
  handle: handle,
  clips: clips,
);

Future<void> timelineComposerPlay({required PlatformInt64 handle}) =>
    RustLib.instance.api.crateApiSimpleTimelineComposerPlay(handle: handle);

Future<void> timelineComposerPause({required PlatformInt64 handle}) =>
    RustLib.instance.api.crateApiSimpleTimelineComposerPause(handle: handle);

Future<void> timelineComposerSeek({
  required PlatformInt64 handle,
  required PlatformInt64 positionMs,
}) => RustLib.instance.api.crateApiSimpleTimelineComposerSeek(
  handle: handle,
  positionMs: positionMs,
);

PlatformInt64 timelineComposerGetPosition({required PlatformInt64 handle}) =>
    RustLib.instance.api.crateApiSimpleTimelineComposerGetPosition(
      handle: handle,
    );

PlatformInt64 timelineComposerGetDuration({required PlatformInt64 handle}) =>
    RustLib.instance.api.crateApiSimpleTimelineComposerGetDuration(
      handle: handle,
    );

bool timelineComposerIsPlaying({required PlatformInt64 handle}) => RustLib
    .instance
    .api
    .crateApiSimpleTimelineComposerIsPlaying(handle: handle);

FrameData? timelineComposerGetLatestFrame({required PlatformInt64 handle}) =>
    RustLib.instance.api.crateApiSimpleTimelineComposerGetLatestFrame(
      handle: handle,
    );

Future<void> timelineComposerDispose({required PlatformInt64 handle}) =>
    RustLib.instance.api.crateApiSimpleTimelineComposerDispose(handle: handle);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VideoPlayer>>
abstract class VideoPlayer implements RustOpaqueInterface {
  @override
  Future<void> dispose();

  /// Extract frame at specific position for preview without seeking main pipeline
  Future<void> extractFrameAtPosition({required double seconds});

  BigInt getCurrentFrameNumber();

  double getDurationSeconds();

  double getFrameRate();

  FrameData? getLatestFrame();

  double getPositionSeconds();

  BigInt getTotalFrames();

  (int, int) getVideoDimensions();

  bool hasAudio();

  bool isPlaying();

  bool isSeekable();

  Future<void> loadVideo({required String filePath});

  factory VideoPlayer() => RustLib.instance.api.crateApiSimpleVideoPlayerNew();

  static VideoPlayer newPlayer() =>
      RustLib.instance.api.crateApiSimpleVideoPlayerNewPlayer();

  Future<void> pause();

  Future<void> play();

  /// Seek to final position with pause/resume control - used when releasing slider
  Future<double> seekAndPauseControl({
    required double seconds,
    required bool wasPlayingBefore,
  });

  Future<void> seekToFrame({required BigInt frameNumber});

  void setTexturePtr({required PlatformInt64 ptr});

  Future<void> stop();

  /// Force synchronization between pipeline state and internal state
  Future<bool> syncPlayingState();

  Future<void> testAudio();

  Future<void> testPipeline({required String filePath});
}
